# Generated by Django 3.1.6 on 2022-01-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addvehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicle',
            name='avgspeed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vechicle',
            name='fuellev',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vechicle',
            name='speed',
            field=models.PositiveIntegerField(),
        ),
    ]
