# Generated by Django 3.1.6 on 2022-01-18 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addvehicle', '0002_auto_20220118_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicle',
            name='fuellev',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
