# Generated by Django 3.1.6 on 2022-01-23 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addvehicle', '0004_vechicle_on_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicle',
            name='avgspeed',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='vechicle',
            name='speed',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
